ci: Add issue auto respond and close workflow
mParticle/mparticle-workflows pull request #61
Opened 2024-12-06 19:07 UTC by rmi22186

## Summary
This workflow allows other `mparticle` repositories to re-use this workflow, such as https://github.com/mParticle/mparticle-web-sdk/pull/958 to automatically comment to an issue creator to redirect them to proper support channels which will make ZD tickets, which will follow our internal ticketing process better.

## Testing Plan
Tested in a personal github repository and it worked there.

## Reference Issue
- Closes https://go.mparticle.com/work/SQDSDKS-6921

2024-12-06 20:00 UTC, alexs-mparticle requested changes

2024-12-06 20:18 UTC, alexs-mparticle approved these changes

2024-12-10 22:39 UTC, einsteinx2 requested changes

2024-12-10 22:39 UTC, einsteinx2 commented on .github/workflows/issue-autorespond-and-close.yml
> +          description: Github Login for User who opened the issue.
```suggestion
        description: Github Login for User who opened the issue.
```
Looks like this had different indentation than the rest of the yaml which can cause problems

2024-12-11 18:05 UTC, einsteinx2 approved these changes

2024-12-11 18:20 UTC, merged